### ISSUE TITLE
Brainstorm list of open source projects that could be the focus of the project

### ISSUE THREAD

**Issue by GregHoff** [team-assure/Semester-Project#1]

**Comment by GregHoff** [comment]
Everyone can add their list here in the comment section

**Comment by SarahNSec** [comment]
https://github.com/team-assure/Semester-Project/blob/master/Project-Proposal/Candidate-Projects.md
https://github.com/team-assure/Semester-Project/blob/master/Project-Proposal/Decision-Matrix.md
